name: Prepare for deployment

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  prepare-for-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0
        with:
          run_install: false
          version: 11

      - name: Install node dependencies
        run: pnpm install --recursive

      - name: Compile typescript
        run: pnpm run build

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "username@users.noreply.github.com"
          git add .
          git commit -m "Prepare for deployment" || echo "No changes to commit"
          git push origin HEAD || echo "No changes to push"